syntax = "proto3";

package pramaan.docreg.v1;

import "pramaan/docreg/v1/tx.proto";
import "pramaan/docreg/v1/params.proto";

option go_package = "pramaan/x/docreg/types";

// Query service
service Query {
  rpc GetDocument(QueryGetDocumentRequest) returns (QueryGetDocumentResponse);
rpc Params(QueryParamsRequest) returns (QueryParamsResponse);}

// --------------------
// DOCUMENT QUERY
// --------------------

message QueryGetDocumentRequest {
  string id = 1;
}

message QueryGetDocumentResponse {
  Document document = 1;
}

// --------------------
// PARAMS QUERY (REQUIRED)
// --------------------

message QueryParamsRequest {}

message QueryParamsResponse {
  Params params = 1;
}